### ISSUE TITLE
Trying out different examples.

### ISSUE THREAD

**Issue by Raviteja1996** [facebookresearch/ReAgent#126]
Hi, I followed the **usage**  documentation and tried the example for dqn_workflow.py. So there are still other files in the ml/rl/workflow directory right!!! but when I try to run those with the command :  **python ml/rl/workflow/ddpg_workflow.py -p ml/rl/workflow/sample_configs/discrete_action/dqn_small.json** I am getting the following error.
Error:
Traceback (most recent call last):
  File "ml/rl/workflow/ddpg_workflow.py", line 189, in <module>
    main(params)
  File "ml/rl/workflow/ddpg_workflow.py", line 131, in main
    params["shared_training"]["minibatch_size"] *= minibatch_size_multiplier(
KeyError: 'shared_training'

So do i need to create the data again for different workflow, for example ddpg_workflow.py, parametric_dqn_workflow.py etc?
And also to try out different examples is there any method there? If I am doing anything wrong please help me.
There are also different models present in the model directory. Can I know how to use them?

I also have a doubt about the On-Policy Training, is one command enough to get the result or that command is used for data creating only? Command: **python ml/rl/test/gym/run_gym.py -p ml/rl/test/gym/discrete_dqn_cartpole_v0.json**. This command is not for training right!

**Comment by czxttkl** [comment]
The error you got is due to that different workflows require slightly different configurations. You mistakenly feed the config that is supposed to feed DQN to DDPG. You can reference to the config for DDPG specifically: (ml/rl/workflow/sample_configs/continuous_action/ddpg_example.json)

I haven't tried using the same dataset for different workflows. My guess is that the dataset generated by one algorithm can be fed into other algorithms of the same category. For example, if you generate data while you run SAC, then probably you can use the data to train DDPG because SAC and DDPG are both continuous-action algorithms.  

A good starting point to explore different models is to try run_gym.py with different configurations.

You can check the source code of run_gym.py. It supports data collection as well as model training. For model training, it also supports either online training (interact with the environment as the model is being updated) or offline training (collect data first and train).
