### ISSUE TITLE
ModuleNotFoundError: No module named 'reagent.core'

### ISSUE THREAD

**Issue by initial-h** [facebookresearch/ReAgent#248]
when I ran python reagent/test/gym/run_gym.py -p reagent/test/gym/discrete_dqn_cartpole_v0.json, I got this error.

**Comment by kittipatv** [comment]
Sorry, we're in the middle of a migration. @kaiwenw can you please update the usage instructions?

**Comment by kaiwenw** [comment]
@initial-h They should be updated now :)

**Comment by xiaohai-AI** [comment]
Dear Sir

I still got the same problem
File "./vlenv/vlreagent/lib/python3.7/site-packages/reagent/types.py", line 12, in <module>
    from reagent.core.dataclasses import dataclass as pydantic_dataclass
ModuleNotFoundError: No module named 'reagent.core'

but I have to say my runing tox is not sucessful
I got nine errors
ERROR: InvocationError for command ~/ReAgent/.tox/py37/bin/pytest -n 4 -m 'not serial' (exited with code 1)

**Comment by rcheu-quora** [comment]
This is because there's a number of missing __init__.py files for various folders, so the modules are not included in the created package.

Here's a patch to fix it.

`diff --git a/reagent/core/__init__.py b/reagent/core/__init__.py
new file mode 100644
index 0000000..e69de29
diff --git a/reagent/gym/envs/dynamics/__init__.py b/reagent/gym/envs/dynamics/__init__.py
new file mode 100644
index 0000000..e69de29
diff --git a/reagent/gym/envs/pomdp/__init__.py b/reagent/gym/envs/pomdp/__init__.py
new file mode 100644
index 0000000..e69de29
diff --git a/reagent/net_builder/__init__.py b/reagent/net_builder/__init__.py
new file mode 100644
index 0000000..e69de29
diff --git a/reagent/workflow/model_managers/__init__.py b/reagent/workflow/model_managers/__init__.py
new file mode 100644
index 0000000..e69de29
diff --git a/reagent/workflow/publishers/__init__.py b/reagent/workflow/publishers/__init__.py
new file mode 100644
index 0000000..e69de29
diff --git a/reagent/workflow/reporters/__init__.py b/reagent/workflow/reporters/__init__.py
new file mode 100644
index 0000000..e69de29
diff --git a/reagent/workflow/validators/__init__.py b/reagent/workflow/validators/__init__.py
new file mode 100644
index 0000000..e69de29
diff --git a/reagent/workflow_utils/__init__.py b/reagent/workflow_utils/__init__.py
new file mode 100644
index 0000000..e69de29`
